# Generated by Django 4.2.4 on 2023-12-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0002_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
